# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97304757bab10bae1668a01d7a8d59f06fbe471ae2a075893b633d4f6331fdef2624552151b4005a45955a46da3a20d6280ba368a960146c34f779439e47ddd6

test:
  secret_key_base: 5ea1b6f173675d47a135aada728546f5b70cac6ad08d5ebde9f37ab338e6c76386993888a937930cb8f1d63753d3bf290dcb2068197bfbd330777d30a2582982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
